# Generated by Django 4.0.4 on 2022-08-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
    ]
